apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Use "nlb" for Network Load Balancer or "elb" for Classic Load Balancer
spec:
  selector:
    app: python-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80   # External Port
      targetPort: 8080  # Port of the application
