apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true" # Use "nlb" for Network Load Balancer or "elb" for Classic Load Balancer
  lables:
    app: python-app
spec:
  selector:
    app: python-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80   # External Port
      targetPort: 5000  # Port of the application
