apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "classic"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
